# Generated by Django 4.0.5 on 2022-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
