# Generated by Django 4.0.5 on 2022-08-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_school_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='school',
            name='hod_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='students_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
