# Generated by Django 4.1 on 2022-08-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_school_hod_name_alter_school_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='hod_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
