# Generated by Django 4.1 on 2022-08-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_school_hod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='hod_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='students_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
